runtime: python37

handlers:
- url: /
  static_files: static/index.html
  upload: static/index\.html
  secure: always
  http_headers:
    Content-Security-Policy: "default-src 'self'"

- url: /
  static_dir: static
  secure: always
